### ISSUE TITLE
Bug: Task in debug exposes secrets

### ISSUE THREAD

**Issue by fgiele** [thycotic/TSS-ADO-BuildTask#4]
When running the task in debug mode, the secrets are exposes in the log.
`2021-03-24T15:26:32.2179523Z ##[debug]set TSS_password=not_so_secret`

Also, when adding the values to a variable in the pipeline, these are not set up as secrets:
`##vso[task.setvariable variable=TSS_password;issecret=false;]not_so_secret`

This means that in a subsequent step, the value of the variable can be made visible in the log, for instance with a simple script:
ECHO $(TSS_password)

**Comment by EndlessTrax** [comment]
Thank you for reporting this. 

We are working on updates to this build task, so we'll be sure to add a fix to this issue as part of the updates.

**Comment by pvanulden** [comment]
There is a pull request in to resolve this. Thanks @fgiele for pointing that out.

https://github.com/thycotic/TSS-ADO-BuildTask/pull/5

**Comment by EndlessTrax** [comment]
PR #5 has been merged. Thank you @pvanulden.

**Comment by inchworksinc** [comment]
Same question as @wsmelton . Is there a plan to publish the fixed version to marketplace?
