### ISSUE TITLE
Secret ID Requirement

### ISSUE THREAD

**Issue by Grime121** [thycotic/TSS-ADO-BuildTask#6]
I'm trying to figure out what Secret ID I am supposed to to put into the Secret ID requirement field. Secret IDs are unique to each secret. If we are trying to look up the secrets so that they can be pulled into/synced with DevOps, we are obviously going to be dealing with more than one secret, and therefore, more than one secret ID. So, which secret's ID is supposed to go in the "Secret ID" field? Do you have to make it a variable, and then add the Secret ID for each secret that you want to "sync" in DevOps? Surely looking up the secret that you need using this task does not require you to know what the secret's ID is, does it? I was expecting to be able to look up secrets by username, or at the very least, by Secret Name.

Maybe I am not fully understanding how this task is supposed to work.... If that's the case, can you please provide some insight? We simply want to be able to update the credentials that we have stored in DevOps with the current credentials that are stored in Secret Server either on a scheduled basis, or prior to running any build/task that requires one or more of those credentials.

**Comment by EndlessTrax** [comment]
Unfortunately, Secret Names are not unique in Secret Server. The only way to pull the correct secret is by its `id`. This is a pattern that is used across all Secret Server integrations, not just this one. 

The secret `id` is in the URL of the secret in Secret Server, which will look something like this: `https://your.secretserver/app/#/secret/10/general`. So in this example, the `id` will be `10`.

**Comment by wsmelton** [comment]
The API now supports using the Secret Name to retrieve the object with the `/secrets` endpoint.

**Comment by Grime121** [comment]
Interesting… do you have an example of how to do this, or a link to updated documentation that describes it further?

**Comment by Grime121** [comment]
I’ll check it out. Thanks, Shawn.
